version: 0.2

env:
  variables:
    APP_TYPE: "dotnet_msbuild-k8s"
    BUILD_TYPE: "full"
    APP_CSPROJ_LOC: "aspnetmvcapp"
    DOCKER_FILE_PATH: "Dockerfile"
    EKS_CLUSTER_NAME: "windows-prod"
    K8S_FILE_PATH: "devops-automation/eks.yaml"
    K8S_REGION: "us-west-2"
    K8S_NAMESPACE: "application"
    #PIPELINE_OVERRIDE: "devops-automation/pipeline-stages.yml"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      dotnet: 3.1
      nodejs: 12.14
    commands:
     - powershell Invoke-Command $($(Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/vijayashankar-g/aws-code-pipeline-install-scripts/master/windows/orbiter-install.ps1)).Content
  build:
    commands:
      - powershell echo "path of the pipeline $Env:ORBITER_PATH"; powershell cd $Env:ORBITER_PATH
      - python start_build.py
